#!/usr/bin/env python3
"""JSON-over-stdio adapter for OpenAI's asynchronous Videos API."""
from __future__ import annotations

import json
import mimetypes
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any
from uuid import uuid4

API_ROOT = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1").rstrip("/")


def emit(value: dict[str, Any], code: int = 0) -> None:
    print(json.dumps(value, ensure_ascii=False), flush=True)
    raise SystemExit(code)


def event(message: str, progress: float | None = None, **payload: Any) -> None:
    print(json.dumps({"kind": "video.adapter-event", "message": message, "progress": progress, **payload}), flush=True)


def headers(content_type: str | None = None) -> dict[str, str]:
    key = os.getenv("OPENAI_API_KEY")
    if not key:
        emit({"status": "error", "error": "OPENAI_API_KEY is not set"}, 2)
    value = {"Authorization": f"Bearer {key}"}
    if content_type:
        value["Content-Type"] = content_type
    return value


def retry_after(error: urllib.error.HTTPError) -> float | None:
    raw = error.headers.get("retry-after") if error.headers else None
    try:
        return float(raw) if raw else None
    except ValueError:
        return None


def request_json(method: str, url: str, body: bytes | None = None, content_type: str | None = None) -> dict[str, Any]:
    req = urllib.request.Request(url, data=body, headers=headers(content_type), method=method)
    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as exc:
        text = exc.read().decode("utf-8", errors="replace")
        if exc.code == 429:
            emit({"status": "rate_limited", "error": text or str(exc), "retry_after": retry_after(exc)}, 75)
        raise RuntimeError(f"OpenAI API HTTP {exc.code}: {text or exc.reason}") from exc


def multipart(fields: dict[str, str], file_field: str, file_path: Path) -> tuple[bytes, str]:
    boundary = f"----studio-{uuid4().hex}"
    chunks: list[bytes] = []
    for name, value in fields.items():
        chunks.extend([
            f"--{boundary}\r\n".encode(),
            f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode(),
            str(value).encode(), b"\r\n",
        ])
    mime = mimetypes.guess_type(file_path.name)[0] or "application/octet-stream"
    chunks.extend([
        f"--{boundary}\r\n".encode(),
        f'Content-Disposition: form-data; name="{file_field}"; filename="{file_path.name}"\r\n'.encode(),
        f"Content-Type: {mime}\r\n\r\n".encode(),
        file_path.read_bytes(), b"\r\n",
        f"--{boundary}--\r\n".encode(),
    ])
    return b"".join(chunks), f"multipart/form-data; boundary={boundary}"


def prompt_for(request: dict[str, Any]) -> str:
    parts = [str(request.get("prompt") or "")]
    preserve = request.get("preserve") or []
    motion = request.get("motion") or []
    avoid = request.get("avoid") or []
    if preserve:
        parts.append("Preserve exactly: " + "; ".join(map(str, preserve)) + ".")
    if motion:
        parts.append("Motion and camera intent: " + "; ".join(map(str, motion)) + ".")
    if avoid:
        parts.append("Do not introduce: " + "; ".join(map(str, avoid)) + ".")
    return "\n".join(parts)


def poll(video_id: str, output_directory: Path, timeout_seconds: float, poll_seconds: float) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_seconds
    latest: dict[str, Any] = {}
    while time.monotonic() < deadline:
        latest = request_json("GET", f"{API_ROOT}/videos/{video_id}")
        status = latest.get("status")
        progress = float(latest.get("progress") or 0) / 100.0
        event(f"OpenAI video job {status}.", progress, provider_job_id=video_id, provider_status=status)
        if status == "completed":
            req = urllib.request.Request(f"{API_ROOT}/videos/{video_id}/content", headers=headers(), method="GET")
            try:
                with urllib.request.urlopen(req, timeout=300) as response:
                    output_directory.mkdir(parents=True, exist_ok=True)
                    path = output_directory / "candidate.mp4"
                    path.write_bytes(response.read())
            except urllib.error.HTTPError as exc:
                if exc.code == 429:
                    emit({"status": "rate_limited", "error": str(exc), "retry_after": retry_after(exc)}, 75)
                raise
            return {"status": "completed", "video_path": str(path), "provider_job_id": video_id,
                    "provider": latest, "notes": ["generated by OpenAI Videos API"]}
        if status == "failed":
            raise RuntimeError(json.dumps(latest.get("error") or {"error": "video generation failed"}))
        time.sleep(poll_seconds)
    raise TimeoutError(f"video job {video_id} did not complete before timeout")


def generate(request: dict[str, Any]) -> dict[str, Any]:
    reference = Path(request["reference_image"]).expanduser().resolve()
    output = Path(request["output_directory"]).expanduser().resolve()
    body, content_type = multipart({
        "model": str(request.get("model") or os.getenv("OPENAI_VIDEO_MODEL", "sora-2")),
        "prompt": prompt_for(request),
        "seconds": str(request.get("seconds") or 4),
        "size": str(request.get("size") or "1280x720"),
    }, "input_reference", reference)
    event("Submitting OpenAI video job.", 0.01)
    job = request_json("POST", f"{API_ROOT}/videos", body, content_type)
    return poll(str(job["id"]), output,
                float(os.getenv("OPENAI_VIDEO_TIMEOUT_SECONDS", "1800")),
                float(os.getenv("OPENAI_VIDEO_POLL_SECONDS", "8")))


def repair(request: dict[str, Any]) -> dict[str, Any]:
    video_id = request.get("provider_job_id")
    if not video_id:
        raise RuntimeError("repair requires provider_job_id from the parent candidate")
    issues = "; ".join(map(str, request.get("repair_issues") or []))
    prompt = prompt_for(request) + f"\nRepair the prior video, concentrating on: {issues}. Preserve all successful motion and identity continuity."
    event("Submitting OpenAI video remix repair.", 0.01, parent_provider_job_id=video_id)
    job = request_json("POST", f"{API_ROOT}/videos/{video_id}/remix",
                       json.dumps({"prompt": prompt}).encode(), "application/json")
    return poll(str(job["id"]), Path(request["output_directory"]).expanduser().resolve(),
                float(os.getenv("OPENAI_VIDEO_TIMEOUT_SECONDS", "1800")),
                float(os.getenv("OPENAI_VIDEO_POLL_SECONDS", "8")))


def main() -> None:
    try:
        request = json.load(sys.stdin)
        operation = request.get("operation")
        result = generate(request) if operation == "generate_video" else repair(request) if operation == "repair_video" else None
        if result is None:
            emit({"status": "error", "error": f"unsupported operation: {operation}"}, 2)
        emit(result)
    except SystemExit:
        raise
    except Exception as exc:
        emit({"status": "error", "error": f"{type(exc).__name__}: {exc}"}, 2)


if __name__ == "__main__":
    main()
